image: "public.ecr.aws/r4s5t9y4/logos/logos-blockchain:test"
imagePullPolicy: IfNotPresent

cfgsync:
  port: 4400
  config: ""

scripts:
  runCfgsyncSh: ""
  runNomosSh: ""
  runNomosNodeSh: ""
  runNomosExecutorSh: ""

validators:
  count: 1
  nodes: []

executors:
  count: 1
  nodes: []

kzg:
  mode: "hostPath"
  hostPathParamsPath: "/kzgrs_test_params/kzgrs_test_params"
  inImageParamsPath: "/opt/nomos/kzg-params/kzgrs_test_params"
  hostPath: "/var/lib/nomos/kzgrs_test_params"
  hostPathType: "Directory"
  storageSize: "1Gi"
